import type { Metadata } from "next";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider"
import { defaultFont } from "@/lib/font-config";
import "./globals.css";
import Provider from "@/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Provider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${defaultFont.className} font-sans antialiased`}
          >
            <ThemeProvider
              attribute="class"
              forcedTheme="dark"
            >
              {children}
            </ThemeProvider>
          </body>
        </html>
      </Provider>
    </ClerkProvider>
  );
}
